
import json
import os
import glob

# Configuration
STATS_FILE = 'health_stats.json'
PLOTS_DIR = 'report/plots'
OUTPUT_TEX = 'report/health_report.tex'

def load_stats():
    with open(STATS_FILE, 'r') as f:
        return json.load(f)

def escape_latex(text):
    if not text: return ""
    return str(text).replace('_', r'\_').replace('%', r'\%')

def generate_tex(stats):
    tex_content = r"""
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{geometry}
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{float}
\usepackage{xcolor}
\usepackage{longtable}

\geometry{a4paper, margin=0.8in}

\title{\textbf{Comprehensive Health Data Analysis}}
\author{Generated by Antigravity}
\date{\today}

\begin{document}

\maketitle

\section{Executive Summary}
This report contains an exhaustive analysis of all health metrics found in the export file.
There are \textbf{""" + str(len(stats)) + r"""} distinct data types recorded.

\tableofcontents
\newpage

\section{Metric Details}
"""
    
    # Sort metrics alphabetically
    for metric_name in sorted(stats.keys()):
        data = stats[metric_name]
        
        safe_name = escape_latex(metric_name)
        unit = escape_latex(data.get('unit', ''))
        
        tex_content += f"\\subsection{{{safe_name}}}\n"
        
        # Stats Table
        tex_content += r"\begin{itemize}" + "\n"
        tex_content += f"    \\item \\textbf{{First Record:}} {escape_latex(data.get('first_record'))}\n"
        tex_content += f"    \\item \\textbf{{Last Record:}} {escape_latex(data.get('last_record'))}\n"
        tex_content += f"    \\item \\textbf{{Total Count:}} {data.get('count')}\n"
        
        if 'min' in data:
            tex_content += f"    \\item \\textbf{{Min:}} {data.get('min'):.2f} {unit}\n"
            tex_content += f"    \\item \\textbf{{Max:}} {data.get('max'):.2f} {unit}\n"
            tex_content += f"    \\item \\textbf{{Average:}} {data.get('avg'):.2f} {unit}\n"
            
        tex_content += r"\end{itemize}" + "\n"
        
        # Image
        # Filename Logic: metric name -> lower -> space to underscore
        clean_filename = metric_name.lower().replace(' ', '_') + '.png'
        # image_path = os.path.join(PLOTS_DIR, clean_filename) 
        # In latex, we refer relative to the tex file usually, or absolute. 
        # Since tex is in report/, and plots are in report/plots/, we use plots/filename
        
        plot_rel_path = f"plots/{clean_filename}"
        
        # Check if plot exists (Python script checks absolute path)
        abs_plot_path = os.path.join(os.path.dirname(OUTPUT_TEX), 'plots', clean_filename)
        
        # Note: We are running this script from the parent dir, so check there
        if os.path.exists(f"report/plots/{clean_filename}"):
             tex_content += r"\begin{figure}[H]" + "\n"
             tex_content += r"\centering" + "\n"
             tex_content += f"\\includegraphics[width=0.9\\textwidth]{{{plot_rel_path}}}\n"
             tex_content += f"\\caption{{Trend for {safe_name}}}\n"
             tex_content += r"\end{figure}" + "\n"
        else:
            tex_content += "\\textit{No trend plot available (insufficient numeric data).}\n"
            
        tex_content += "\n\\hrule\\vspace{1em}\n"

    tex_content += r"\end{document}"
    return tex_content

if __name__ == "__main__":
    try:
        if not os.path.exists(STATS_FILE):
             print(f"Stats file {STATS_FILE} not found. Run parse_health_data.py first.")
             exit(1)
             
        stats = load_stats()
        tex = generate_tex(stats)
        
        with open(OUTPUT_TEX, 'w') as f:
            f.write(tex)
            
        print(f"Report generated: {OUTPUT_TEX}")
    except Exception as e:
        print(f"Error: {e}")
